export const ADD_BUN: "ADD_BUN" = "ADD_BUN";
export const ADD_FILLING: "ADD_FILLING" = "ADD_FILLING";
export const DELETE_FILLING: "DELETE_FILLING" = "DELETE_FILLING";
export const CHANGE_FILLING_POSITION: "CHANGE_FILLING_POSITION" = "CHANGE_FILLING_POSITION";