export const GET_INGREDIENS_REQUEST: "GET_INGREDIENS_REQUEST" = "GET_INGREDIENS_REQUEST";
export const GET_INGREDIENS_SUCCESS: "GET_INGREDIENS_SUCCESS" = "GET_INGREDIENS_SUCCESS";
export const GET_INGREDIENS_FAILED: "GET_INGREDIENS_FAILED" = "GET_INGREDIENS_FAILED";

export const SET_CURRENT_TAB: "SET_CURRENT_TAB" = "SET_CURRENT_TAB";



