export const GET_INGREDIENS_REQUEST = "GET_INGREDIENS_REQUEST";
export const GET_INGREDIENS_SUCCESS = "GET_INGREDIENS_SUCCESS";
export const GET_INGREDIENS_FAILED = "GET_INGREDIENS_FAILED";

export const SET_CURRENT_TAB = "SET_CURRENT_TAB";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED = "GET_ORDER_FAILED";
export const SET_ORDER_MODAL = 'SET_ORDER_MODAL';
export const RESET_ORDER_MODAL = 'RESET_ORDER_MODAL';

export const ADD_BUN = "ADD_BUN";
export const ADD_FILLING = "ADD_FILLING";
export const DELETE_FILLING = "DELETE_FILLING";
export const CHANGE_FILLING_POSITION = "CHANGE_FILLING_POSITION";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";

