export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";
export const SET_ORDER_MODAL: 'SET_ORDER_MODAL' = 'SET_ORDER_MODAL';
export const RESET_ORDER_MODAL: 'RESET_ORDER_MODAL' = 'RESET_ORDER_MODAL';


export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";